### ISSUE TITLE
mpv-single-instance feature request

### ISSUE THREAD

**Issue by Pillgar** [dglava/pkgbuilds#1]
Hello dglava.

I love your mpv single-instance script, but I have a request.  I noticed when I select multiple files, they all open in a separate instance at the same time.  The default behavior is to add them all to a playlist.  Is it possible for your pkg to handle multiple selections in the same way?  changing %f to %U in the .desktop did open only one instance, but wouldn't create a playlist.

**Comment by dglava** [comment]
I've never noticed that so far. I'll try and come up with a solution to that.

**Comment by dglava** [comment]
Can you build the latest package and see if it works as expected now?

**Comment by Pillgar** [comment]
You sir are my hero!!!!!!  TYVM and all the best!!!!!
